url: http://arnolanglade.github.io/
baseurl: .

# Site settings
title: Arnaud Langlade
author: Arnaud Langlade
description: "Software engineer @convelio and former core developer @sylius and @akeneo. Love DDD, BDD, TDD, event storming, example mapping"
