version: '3.4'

services:
    web:
        image: 'httpd:2.4'
        ports:
            - '${DOCKER_PORT_WEB_API:-8003}:80'
        volumes:
            - './_site:/usr/local/apache2/htdocs/:ro'

    blog-builder:
        image: 'jekyll/jekyll:latest'
        volumes:
            - '.:/srv/jekyll'
        environment:
            JEKYLL_ENV: development
